# Generated by Django 3.0.8 on 2020-08-15 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200814_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
