# Generated by Django 3.0.8 on 2020-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(db_index=True, max_length=64, verbose_name='Логин')),
                ('password', models.CharField(db_index=True, max_length=64, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=64, verbose_name='Фамилия')),
                ('log', models.CharField(db_index=True, max_length=64, verbose_name='Логин')),
                ('password', models.CharField(db_index=True, max_length=64, verbose_name='Пароль')),
                ('password_replay', models.CharField(db_index=True, max_length=64, verbose_name='Повторите пароль ')),
            ],
        ),
    ]
