# Generated by Django 3.0.8 on 2020-07-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
